/* eslint-disable prettier/prettier */

/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({

  Logo: {
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 100,
  },
  logoText: {
    alignSelf: 'center',
    textAlign: 'center',
    fontSize: 16,
    color: 'black',
    marginVertical: 5,
    fontFamily: 'ProximaNova-Nova',
  },
    container2: {
        width: '85%',
        alignSelf: 'center',
    },
    input1: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingVertical: 0,
        height: 50,
        borderRadius: 10,
        marginVertical: 10,
    },
    userText: {
        width: '73%',
        fontSize: 16,
        fontWeight: '400',
         marginLeft: 15,
    },
    password :{
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center', backgroundColor: '#FFFFFF',
        paddingVertical: 0,
        height: 50,
        borderRadius: 10},
    passwordText: {
        width: '73%',
        fontWeight: '400',
        marginLeft: 15,
        fontSize: 16,
    },
    checkboxBody: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 10, paddingHorizontal: 10,
        alignItems: 'center',
    },
    checkboxButton: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    checkboxText: {
        marginLeft: 10,
        color: '#000000',
        fontSize:14,
        fontFamily: 'Proxima-Nova',
    },
    forgotPassword: {
        color: '#868A9A',
        fontSize: 14,
    },
    loginButton: {
        width: '100%',
        paddingVertical: 0,
        height: 50,
        marginVertical: 5,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
    },
    loginButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '400',
    },
    socialButton: {
        width: '85%',
        alignSelf: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
      },
      facebookButton: {
        borderWidth: 1,
        flex: 1,
        backgroundColor: '#F6F8FB',
        padding: 5,
        paddingVertical: 3,
        marginVertical: 5,
        margin: 5,
        borderRadius: 10,
        alignItems: 'center',
      },
      buttonText: {
        color: 'black',
        textAlign: 'center',
        fontSize: 14,
        fontFamily: 'ProximaNova-Regular',
      },
      socialText: {
        fontSize: 12,
        color: 'black',
      },
      googleButton: {
        borderWidth: 1,
        flex: 1,
        backgroundColor: '#F6F8FB',
        padding: 5,
        paddingVertical: 3,
        marginVertical: 5,
        margin: 5,
        borderRadius: 10,
        alignItems: 'center',
      },
      appleButton: {
        borderWidth: 1,
        flex: 1,
        backgroundColor: '#F6F8FB',
        padding: 5,
        paddingVertical: 3,
        marginVertical: 5,
        margin: 5,
        borderRadius: 10,
        alignItems: 'center',
      },
      signUpButtonText: {
        color: '#F39200',
        fontSize: 14,
       alignSelf: 'flex-end',
        marginVertical: 10,
      },
      signUpButton: {
        width: '90%',
        alignSelf: 'center',
        paddingVertical: 0,
        height: 40,
        marginVertical: 5,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
      },
      popupContainer:{
        backgroundColor: 'white',
        marginVertical: '5%',
        borderWidth: 1,
        borderColor: 'lightgray',
        borderRadius: 10,
        width: '100%',
        alignSelf: 'center',
        padding: 10,
    },
    popupMessageText:{
      alignSelf: 'center',
      marginBottom: '5%',
      textAlign: 'center',
  },
});
